name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel in-progress runs on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-size-check:
    name: PR Size Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate PR size
        id: pr-size
        run: |
          # Get the base branch (target branch)
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          
          # Count additions and deletions
          ADDITIONS=$(git diff --numstat origin/$BASE_BRANCH...HEAD | awk '{sum += $1} END {print sum}')
          DELETIONS=$(git diff --numstat origin/$BASE_BRANCH...HEAD | awk '{sum += $2} END {print sum}')
          TOTAL_CHANGES=$((ADDITIONS + DELETIONS))
          
          echo "additions=$ADDITIONS" >> $GITHUB_OUTPUT
          echo "deletions=$DELETIONS" >> $GITHUB_OUTPUT
          echo "total=$TOTAL_CHANGES" >> $GITHUB_OUTPUT
          
          # Determine size category
          if [ $TOTAL_CHANGES -lt 50 ]; then
            echo "size=XS" >> $GITHUB_OUTPUT
          elif [ $TOTAL_CHANGES -lt 200 ]; then
            echo "size=S" >> $GITHUB_OUTPUT
          elif [ $TOTAL_CHANGES -lt 500 ]; then
            echo "size=M" >> $GITHUB_OUTPUT
          elif [ $TOTAL_CHANGES -lt 1000 ]; then
            echo "size=L" >> $GITHUB_OUTPUT
          elif [ $TOTAL_CHANGES -lt 2000 ]; then
            echo "size=XL" >> $GITHUB_OUTPUT
          else
            echo "size=XXL" >> $GITHUB_OUTPUT
          fi

      - name: PR size summary
        run: |
          echo "✅ PR Size Analysis Complete"
          echo "📊 Changes: +${{ steps.pr-size.outputs.additions }} -${{ steps.pr-size.outputs.deletions }}"
          echo "📏 Size Category: ${{ steps.pr-size.outputs.size }}"
          echo "💡 This information helps reviewers understand the scope of changes"
          
          if [ "${{ steps.pr-size.outputs.size }}" = "XXL" ]; then
            echo "ℹ️ This is a large PR - consider breaking it into smaller chunks for future PRs"
            echo "However, large PRs are acceptable for major feature additions like this one"
          fi